name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: ".tool-versions"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: open-ews-website
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Documentation Source
        uses: actions/download-artifact@v5
        with:
          name: open-ews-website
          path: website

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ap-southeast-1

      - name: Deploy Website
        run: aws s3 sync --delete --exclude docs/api/* --exclude staging/docs/api/* website s3://${{ secrets.OPEN_EWS_WEBSITE_BUCKET_ID }}

      - name: Invalidate Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.OPEN_EWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
